### PR TITLE
Category pages

### PR DESCRIPTION
**Pull request by imkieransmith**
The category page template is built for issue #57

I've pulled the site routes out and concatenate them with category routes. The category routes are hard coded for now but could be loaded through the Statamic content API - I'm unsure on how the routes are compiled and didn't want each page load to hang while loading routes from the API. I'll research this more, or could someone with more Vue Router experience jump in to advise?

I've used the wireframes as a guide but had to change some things around, especially in the banner. Some categories (e.g. carbon-reduction) have too much text to put it alongside an image, so I split it out into the header/intro and image, then a category description section, then the actions.

There doesn't appear to be a defined primary colour so I went with a dark blue to complement the pink hyperlinks. Let me know if this needs changing.

Some further work needs doing on surrounding sections of the site, eg, the navigation bar and the "Want to help? Great!" section, however it looks like these are being addressed in a few other issues.

Some work on #40 is done too, the featured actions are loaded from the API, ready to be built/styled.

### CODE REVIEW

**Comment by philsturgeon** [comment]
Thank you! Strangely when looking on the deploy preview I can't load any of the categories, I just get a white screen when I click on any of the Act Now links on the homepage, in FF and Safari. 

Loading the category URLs directly is a 404 

https://deploy-preview-65--protect-earth-v2.netlify.app/clothing

Any ideas?

**Comment by philsturgeon** [comment]
@ijpatricio could you also review this? seems like we've got a big chunk of progress coming but its got a few troubles.

**Comment by imkieransmith** [comment]
I've never used Netlify automated builds so my research on this hasn't resulted in much. Input from @ijpatricio would be great. Could you also send me some details about how the preview builds are generated? Might help with debugging.

**Comment by philsturgeon** [comment]
I'm not sure it's netlify causing trouble this time (although its not impossible!) I'm seeing this, is it related?

image

**Comment by philsturgeon** [comment]
Thank you so much @imkieransmith, using your branch @mbifulco was able to get this over the finish line. Keep em coming! 🥳

**Comment by imkieransmith** [comment]
Glad the issue sorted, thanks @mbifulco for the help!

**Pull request closed without merging**
